spring.application.name: api-gatway

jwt:
    secretKey: ifejnkjno1298jnoiugcqweb7HGGjibnwklnxobujubwfoqiu78

eureka.client.service-url.defaultZone: http://discovery-service:8761/eureka
#eureka.client.service-url.defaultZone: http://localhost:8761/eureka
eureka.instance.preferIpAddress: true


server.port: 8080


spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - name: AuthenticationFilter
#          filters:
#            - StripPrefix=2

        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/posts/**
          filters:
            - name: AuthenticationFilter
#          filters:
#            - StripPrefix=2

        - id: connections-service
          uri: lb://CONNECTIONS-SERVICE
          predicates:
            - Path=/connections/**
          filters:
            - name: AuthenticationFilter
#          filters:
#            - StripPrefix=2
